### ISSUE TITLE
No GPU process shown in the list, but Firefox working fine

### ISSUE THREAD

**Issue by ColourGrey** [b0bh00d/crash-firefox#4]
I do not know whether this is a bug or not: in the attached screenshot I am using Firefox just fine (notice that in the background I am playing a Youtube video), but there is no "firefox.exe.gpu" process in the list of processes displayed by CrashFirefox. Is this normal?
![No GPU process](https://user-images.githubusercontent.com/57685970/214804696-394c45dd-6373-4dea-a06c-a948d31e81af.png)

Windows 10 64bit, AMD cpu + gpu (integrated)

**Comment by b0bh00d** [comment]
It likely means the application cannot accurately identify the Firefox process that has been designated as such by its command-line arguments.  For example, here is what I see on my system using [Process Explorer](https://learn.microsoft.com/en-us/sysinternals/downloads/process-explorer):

![procexp64_2023-01-26_07-17-37](https://user-images.githubusercontent.com/4536448/214859384-dd50e598-3dda-410b-b825-40041699fce2.png)

Note the `gpu` tag at the end of the line.  You might grab PE and have a look at your running Firefox processes and see if you can visually identify the GPU process in this way.

**Comment by ColourGrey** [comment]
I understand. Well, there is no Firefox process currently running on my system with "gpu" at the end of the command line. All the processes launched by the main one have one of "tab", "utility", "rdd" or "socket" at the end, but no "gpu". Yet Firefox works correctly. Should I understand that the "gpu" process is not mandatory for displaying stuff (in particular video)?

**Comment by b0bh00d** [comment]
I'm just guessing, but it may be that your particular Intel GPU is blocklisted for some reason, and Firefox is running in software-only mode (i.e., CPU).  Your CPU is probably powerful enough to handle most regular web content, so you aren't noticing any/much degradation.

That's actually how I run Firefox on my desktop, because my CPU has 28 logical cores, and it's powerful enough without having to rely on the GPU for acceleration.

If you open `about:support` and look for `WebRender` (in the Graphics section), my guess is it will probably say `WebRender (Software)`.

**Comment by ColourGrey** [comment]
Indeed, this is what is happening (the CPU is AMD, not Intel, but this changes nothing). Firefox is causing me troubles under certain circumstances, and when this happens I kill the gpu process with CrashFirefox. Usually it is respawned immediately and automatically, but not today. Strange.

Anyway, thank you. I am going to close this since there is no CrashFirefox bug to address, in fact.
